# Generated by Django 5.2.1 on 2025-06-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('bathrooms', models.IntegerField()),
                ('age_of_property', models.IntegerField(help_text='Age of the property in years')),
                ('sale_type', models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent'), ('sold', 'Sold')], max_length=50)),
                ('build_area', models.DecimalField(decimal_places=2, help_text='Area in square feet', max_digits=10)),
                ('plot_area', models.DecimalField(decimal_places=2, help_text='Plot area in square feet', max_digits=10)),
                ('amenities', models.TextField(blank=True, choices=[('swimming_pool', 'Swimming Pool'), ('gym', 'Gym'), ('garden', 'Garden'), ('parking', 'Parking'), ('security', 'Security'), ('wifi', 'Wi-Fi'), ('air_conditioning', 'Air Conditioning'), ('heating', 'Heating'), ('furnished', 'Furnished'), ('balcony', 'Balcony')], help_text='List of amenities available', null=True)),
                ('balcony_no', models.IntegerField(default=0, help_text='Number of balconies')),
                ('parking_no', models.IntegerField(default=0, help_text='Number of parking spaces')),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('condo', 'Condo'), ('land', 'Land'), ('commercial', 'Commercial')], max_length=50)),
                ('image', models.URLField(blank=True, null=True)),
                ('bedrooms', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
