# Generated by Django 5.2.1 on 2025-06-16 07:26

import aoo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.CharField(default=aoo.models.generate_unique_id, editable=False, max_length=5, primary_key=True, serialize=False, unique=True),
        ),
    ]
