# Generated by Django 5.2.1 on 2025-06-16 10:01

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoo', '0004_alter_propertyimage_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='property',
            name='amenities',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('swimming_pool', 'Swimming Pool'), ('gym', 'Gym'), ('garden', 'Garden'), ('parking', 'Parking'), ('security', 'Security'), ('wifi', 'Wi-Fi'), ('air_conditioning', 'Air Conditioning'), ('heating', 'Heating'), ('furnished', 'Furnished'), ('balcony', 'Balcony')], max_length=89, null=True),
        ),
    ]
