# Generated by Django 5.2.1 on 2025-06-16 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aoo', '0005_amenity_alter_property_amenities'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Amenity',
        ),
    ]
