# Generated by Django 5.2.1 on 2025-06-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aoo', '0006_delete_amenity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='image_id',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
